# Generated by Django 3.0.5 on 2021-03-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categories_comment_genres_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.CharField(blank=True, help_text='Описание тайтла', max_length=50, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='title',
            name='titles_id',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
