# Generated by Django 3.0.5 on 2021-03-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210327_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(blank=True, help_text='Поиск по категории', max_length=50, null=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genres',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
